name: Build execmd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install rush
        run: npm install -g @microsoft/rush
        # run: node common/scripts/install-run-rush.js install
      - name: Check that dependency versions across projects are consistent
        run: rush check
      - run: rush install --no-link
      - run: rush link
      - name: Check that there are no audit issues with any of the dependencies
        run: |
          cd ./common/temp
          pnpm audit
      - run: rush build --verbose
