name: Build execmd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install rush
        run: node common/scripts/install-run-rush.js install
      - run: rush install --no-link
      - run: rush link
      - run: rush build --verbose
