name: Build exec-md

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install rush
        run: npm install -g @microsoft/rush pnpm npm-check-updates

      - name: Check that dependency versions across projects are consistent
        run: rush check

      - name: Install dependencies
        run: rush install --no-link

      - name: Link dependencies
        run: rush link

      - name: Check that there are no audit issues with any of the dependencies
        run: |
          cd ./common/temp
          pnpm audit

      - name: Build and test exec-md
        run: rush build --verbose
