name: Check Audit Issues

on:
  schedule:
    - cron: "0 0 12 * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install node modules
        run: npm install -g @microsoft/rush pnpm

      - name: Install dependencies
        run: rush install --no-link

      - name: Link dependencies
        run: rush link

      - name: Check that there are no audit issues with any of the dependencies
        run: |
          cd ./common/temp
          pnpm audit
